---
- name: Setting Output File Name
  set_fact:
    aci_query_title: 'bundle_policy_groups'
  tags: always

- name: Applying API Path JSON Query Filter
  set_fact:
    api_query_filter: '/api/node/class/infraAccBndlGrp.json?query-target=subtree&target-subtree-class=infraAccBndlGrp&rsp-subtree=full'
  tags: always

- name: Run Query
  include_tasks: run-query.yml
  tags: always

- name: Copy Response to Disk
  copy: 
    content: '{{ aci_response }}' 
    dest: '{{ temp_dir.path }}/{{ aci_query_title }}.json'
  tags: always
